services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_shop_pos
    ports:
      - '5432:5432'
    volumes:
      - coffee_shop_pos_pgdata:/var/lib/postgresql/data

volumes:
  coffee_shop_pos_pgdata:
